#!/usr/bin/env python
# coding: utf-8

from openquake.baselib import sap
from openquake.wkf.ses import check_ses_vs_catalogue


def main(fname, example_flag=False):
    """
    Confronts the seismicity contained in a stochastic event set generated by
    the engine against a real earthquake catalogue.
    """
    check_ses_vs_catalogue(fname, example_flag)


descr = 'Name of the .toml configuration file'
main.fname = descr
descr = 'A flag. When true the code prints an example of .toml configuration'
main.example_flag = descr

if __name__ == '__main__':
    sap.run(main)
