sudo: false

language: python

cache: pip

python:
 - "3.6"

env:
  - MPLBACKEND=Agg

install:
  - git clone --depth=1 https://github.com/gem/oq-engine.git &&
    pip -q install -r oq-engine/requirements-py36-linux64.txt &&
    pip -q install -e oq-engine
  - pip -q install http://cdn.ftp.openquake.org/wheelhouse/linux/py36/pyproj-1.9.5.1-cp36-cp36m-manylinux1_x86_64.whl
  - pip -q install http://cdn.ftp.openquake.org/wheelhouse/linux/py36/GDAL-2.2.4-cp36-cp36m-manylinux1_x86_64.whl
  - pip -q install http://cdn.ftp.openquake.org/wheelhouse/linux/py36/Rtree-0.8.3-cp36-cp36m-manylinux1_x86_64.whl
  - pip install -e .

script:
  - nosetests -vsx -a '!slow'
