language: python

cache: pip

python:
 - "3.8"

env:
  - MPLBACKEND=Agg

install:
  - sudo apt install libspatialindex-dev
  - git clone --depth=1 https://github.com/gem/oq-engine.git &&
    pip -q install -r oq-engine/requirements-py38-linux64.txt -r oq-engine/requirements-extra-py38-linux64.txt && pip install -e .

script:
  - nosetests -vsx -a '!slow'

notifications:
  email:
    recipients:
      - marco.pagani@globalquakemodel.org
      - michele.simionato@globalquakemodel.org
    on_success: never
    on_failure: always
