sudo: false

language: python

cache: pip

python:
 - "3.6"

env:
  - MPLBACKEND=Agg

install:
  - git clone --depth=1 https://github.com/gem/oq-engine.git &&
    pip -q install -r oq-engine/requirements-py36-linux64.txt -r oq-engine/requirements-extra-py36-linux64.txt &&
    pip -q install -e oq-engine
  - pip -q install -r requirements-py36-linux64.txt &&
    pip install -e .

jobs:
  include:

  - stage: test
    script:
      - nosetests -vsx -a '!slow'
    deploy:

  - stage: pages
    script:
      - pip install sphinx
      - pip install recommonmark
      - pip install sphinx_rtd_theme
      - cd docsrc ; sphinxs-apidoc -o contents/ ../openquake ; make html
      - touch _build/html/.nojekyll


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docsrc/_build/html/
  on:
    branch:
      - master
      - docs


notifications:
  email:
    recipients:
      - marco.pagani@globalquakemodel.org
      - michele.simionato@globalquakemodel.org
    on_success: never
    on_failure: always
