sudo: false

language: python

cache: pip

python:
 - "3.5"

install:
  - pip install openquake.engine
  - pip install http://cdn.ftp.openquake.org/wheelhouse/linux/py35/pyproj-1.9.5.1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://cdn.ftp.openquake.org/wheelhouse/linux/py35/GDAL-2.2.4-cp35-cp35m-manylinux1_x86_64.whl 
  - pip install http://cdn.ftp.openquake.org/wheelhouse/linux/py35/Rtree-0.8.3-cp35-cp35m-manylinux1_x86_64.whl 
  - pip install .

script:
  - nosetests -vsx 
