[models]

[models.AbrahamsonEtAl2014]

[models.BooreEtAl2020]

[models.CampbellBozorgnia2014]

[models.KothaEtAl2020]

[models.LanzanoEtAl2019_RJB_OMO]

[imts]
imt_list = ["PGA","SA(0.2)","SA(0.6)", "SA(1.0)"]