### Input file for comparison of GMPEs using plotting functions in openquake.smt.comparison.compare_gmpes

[general]
name_analysis = 'demo_comparison_analysis_inputs'
imt_list = ['PGA', 'SA(0.2)', 'SA(1.0)']
max_period = 2 # max period for spectra plots
minR = 0 # min dist. used in trellis, Sammon's, clusters and matrix plots
maxR = 300 # max dist. used in trellis, Sammon's, clusters and matrix plots
dist_type = 'repi' # or rrup, rjb, rhypo (dist type used in trellis plots)
dist_list = [10, 100, 250] # distance intervals for use in spectra plots
Nstd = 0 # num. of std. dev. to sample from sigma distribution

# Specify site properties
[site_properties]
vs30 = 800
Z1 = -999   # If -999 compute from Vs30 using Chiou and Youngs (2014) relationship
Z25 = -999  # If -999 compute from Vs30 using Campbell and Bozorgnia (2014)
up_or_down_dip = 1 # 1 = up-dip, 0 = down-dip
z_basin_region = 'Global' # Obtain z1pt0/z2pt5 from "Global" or "JPN" (Japan) empirical Vs30-based relationships if z1pt0 or z2pt5 not specified above
volc_back_arc = false # true or false

# Characterise earthquake for the region of interest as finite rupture
[source_properties]
trt = 'None' # Either string of 'None' to use user-provided aratio OR specify a TRT string from ASCR, InSlab, Interface, Stable, Upper_Mantle, Volcanic, Induced, Induced_Geothermal to assign a trt-dependent proxy aratio
ztor = 'None' # Set to string of 'None' to NOT consider else list corresponding to number of mags/depths
strike = -999
dip =  60
rake = 90 # Must be provided. Strike and dip can be approximated if set to -999
aratio = 2 # If set to -999 the user-provided trt string will be used to assign a trt-dependent aratio
trellis_and_rs_mag_list = [5, 6, 7] # mags used only for trellis and response spectra
trellis_and_rs_depths = [20, 20, 20] # depth per magnitude and response spectra

# Specify magnitude array for Sammons, Euclidean dist and clustering
[mag_values_non_trellis_or_spectra_functions]
mmin = 5
mmax = 7
spacing = 0.1
non_trellis_or_spectra_depths = [[5, 20], [6, 20], [7, 20]] # [[mag, depth], [mag, depth], [mag, depth]] 

# Specify label for gmpes
[gmpe_labels]
gmpes_label = ['B20', 'L19', 'K1', 'K2', 'K3', 'K4', 'K5', 'CB14', 'AK14']

# Specify gmpes

# Plot logic tree and individual GMPEs for below GMC logic tree config (gmc1)
[models.BooreEtAl2020]
lt_weight_gmc1 = 0.3
    
[models.LanzanoEtAl2019_RJB_OMO]
lt_weight_gmc1 = 0.40

# Default K20_ESHM20 logic tree branches considered in gmc1
[models.1-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.000862
sigma_mu_epsilon = 2.85697 
c3_epsilon = 1.72    

[models.2-KothaEtAl2020ESHM20]   
lt_weight_gmc1 = 0.067767
sigma_mu_epsilon = 1.35563
c3_epsilon = 0

[models.3-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.162742
sigma_mu_epsilon = 0
c3_epsilon = 0        

[models.4-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.067767
sigma_mu_epsilon = -1.35563
c3_epsilon = 0 

[models.5-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.000862
sigma_mu_epsilon = -2.85697 
c3_epsilon = -1.72    
        
# Plot logic tree only for the second GMC logic tree config (gmc2)
[models.CampbellBozorgnia2014]
lt_weight_gmc2_plot_lt_only = 0.50
estimate_ztor=true

[models.AkkarEtAlRjb2014]
lt_weight_gmc2_plot_lt_only = 0.50
    
# Also specify a GMM to compute ratios of the attenuation against (GMM/baseline)
[ratios_baseline_gmm.BooreEtAl2020]

[custom_colors]
custom_colors_flag = false # Set to true for custom colours in plots)
custom_colors_list = ['lime', 'dodgerblue', 'gold', '0.8']