[models]

[models.AbrahamsonEtAl2014]

[models.AkkarEtAlRjb2014]

[models.BooreEtAl2014]

[models.BooreEtAl2020]

[models.CauzziEtAl2014]

[models.CampbellBozorgnia2014]

[models.ChiouYoungs2014]

[models.KothaEtAl2020]

[models.LanzanoEtAl2019_RJB_OMO]

[imts]
imt_list = ["PGA","SA(0.1)","SA(0.2)","SA(0.5)","SA(1.0)","SA(2.0)"]