name: Python application for 3.8
on:
  push:

jobs:

  test:
    name: hazard test
    runs-on: ubuntu-18.04
    env:
      MPLBACKEND: 'Agg'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        git clone --depth=1 https://github.com/gem/oq-engine.git
        pip -q install -r oq-engine/requirements-py38-linux64.txt -r oq-engine/requirements-extra-py38-linux64.txt
        pip -q install -e oq-engine
        pip install rtree-linux 
        pip install -e .
    - name: Run test with pytest
      run: |
        cd openquake
        pytest -vsx mbt cat man sub

  pages:
    name: pages
    runs-on: ubuntu-18.04
    env:
      MPLBACKEND: 'Agg'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install pandoc
        pip install sphinx
        pip install recommonmark
        pip install sphinx_rtd_theme
        pip install nbsphinx
        cd docsrc ; sphinx-apidoc -o contents/ ../openquake ; make html
        touch _build/html/.nojekyll


